title: #### Alexio Junior Aaron
logo: /assets/img/logo.png
description: * Machine Learning Engineer
             * Previously Backend Engineer (Django)
             * I love challenges and help others if they need my help at any time
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
